version: '3.9'

services:
  db:
    image: postgres:17
    container_name: oniria_db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://devuser:devpass@db:5432/devdb
      DB_HOST: db
      HOST: 0.0.0.0
      PORT: 8000
      RELOAD: "true"
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/oniria-back

volumes:
  pgdata:
